#!/usr/bin/env python3
"""
01_gtf_to_bed.py
================

Turn a GENCODE / Ensembl style GTF annotation file into a set of standard BED
files, one per transcriptome feature class:

    genes.bed            one row per gene
    transcripts.bed      one row per transcript
    exons.bed            every exon of every transcript (coding and non-coding)
    coding_exons.bed     only the translated part of each exon (the CDS blocks)
    five_prime_utrs.bed  5' UTR blocks
    three_prime_utrs.bed 3' UTR blocks
    introns.bed          the gaps between consecutive exons of a transcript

Usage
-----
    # run from the repository root
    python task1_gtf_features/scripts/01_gtf_to_bed.py \
        --gtf data/gencode.v33.annotation.gtf.gz \
        --outdir task1_gtf_features/bed_features

Only the Python standard library is used, so there is nothing to install.
"""

import argparse
import gzip
import os
import re
import sys
import time
from collections import defaultdict


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

def log(message):
    """Print progress to stderr so that stdout stays clean for piping."""
    sys.stderr.write("[{}] {}\n".format(time.strftime("%H:%M:%S"), message))
    sys.stderr.flush()


def open_maybe_gzip(path):
    """Open a plain text or a gzipped text file transparently.
    """
    with open(path, "rb") as probe:
        magic = probe.read(2)
    if magic == b"\x1f\x8b":
        return gzip.open(path, "rt", encoding="utf-8")
    return open(path, "r", encoding="utf-8")


# The GTF attribute column looks like:
#   gene_id "ENSG00000223972.5"; gene_name "DDX11L1"; exon_number 1; tag "basic";
# Values may or may not be quoted. This regex grabs key plus value for both cases.
_ATTR_RE = re.compile(r'(\S+)\s+"?([^";]+)"?;')

# We only care about a handful of attribute keys. Checking membership in a small
# set is far cheaper than building a dictionary of all ~15 attributes for each
# of the ~2.9 million lines in the file..
_WANTED_ATTRS = frozenset([
    "gene_id", "gene_name", "gene_type",
    "transcript_id", "transcript_name", "transcript_type",
    "exon_number",
])


def parse_attributes(attr_string):
    """Pull the attributes we care about out of GTF column 9.

    Returns a plain dict. 
    """
    found = {}
    for key, value in _ATTR_RE.findall(attr_string):
        if key in _WANTED_ATTRS:
            found[key] = value
    return found


def natural_chrom_key(chrom):
    """Sort key that orders chromosomes the way a human would expect.

    chr1, chr2, ... chr9, chr10 ... chr22, chrX, chrY, chrM, then everything
    else (scaffolds, alts, randoms) alphabetically at the end.
    """
    name = chrom[3:] if chrom.startswith("chr") else chrom
    if name.isdigit():
        return (0, int(name), "")
    if name in ("X", "Y"):
        return (1, 0, name)
    if name in ("M", "MT"):
        return (2, 0, name)
    return (3, 0, chrom)


def subtract_intervals(block, holes):
    """Return the parts of `block` that are not covered by any interval in `holes`.
    """
    start, end = block
    pieces = []
    cursor = start
    for hole_start, hole_end in holes:
        if hole_end <= cursor:
            continue          # this hole is entirely behind us, skip it
        if hole_start >= end:
            break             # holes are sorted, so everything after is past us
        if hole_start > cursor:
            pieces.append((cursor, hole_start))   # gap found before the hole
        cursor = max(cursor, hole_end)
        if cursor >= end:
            break
    if cursor < end:
        pieces.append((cursor, end))   # trailing piece after the last hole
    return pieces


def merge_intervals(intervals):
    """Merge a list of (start, end) pairs into the smallest non-overlapping set.
    """
    if not intervals:
        return []
    ordered = sorted(intervals)
    merged = [list(ordered[0])]
    for start, end in ordered[1:]:
        if start <= merged[-1][1]:           
            merged[-1][1] = max(merged[-1][1], end)
        else:
            merged.append([start, end])
    return [(s, e) for s, e in merged]


# ---------------------------------------------------------------------------
# BED writing
# ---------------------------------------------------------------------------

BED_HEADER_NOTE = (
    "# Generated by 01_gtf_to_bed.py\n"
    "# Columns 1-6 follow the standard BED6 spec: chrom, chromStart (0-based),\n"
    "# chromEnd (exclusive), name, score, strand. Any further columns are extra\n"
    "# metadata and are safe for tools to ignore.\n"
)


class BedWriter(object):
    """Collects BED rows in memory, then sorts and writes them once at the end.

    Sorting matters: almost every downstream tool (bedtools intersect, tabix,
    and our own chromosome-blocked mapping script) is either faster or outright
    requires coordinate-sorted input. GTF files are grouped by gene rather than
    strictly sorted, so we cannot just stream straight through.
    """

    def __init__(self, path, extra_column_names, write_header):
        self.path = path
        self.extra_column_names = extra_column_names
        self.write_header = write_header
        self.rows = []

    def add(self, chrom, start, end, name, strand, extras):
        """Queue one BED row. `extras` is a tuple of the extra metadata columns."""
        # A zero or negative length interval is meaningless in BED and would
        # silently break overlap logic later, so we refuse to emit one.
        if end <= start:
            return False
        self.rows.append((chrom, start, end, name, strand, extras))
        return True

    def flush(self):
        """Sort by chromosome then position, then write the file to disk."""
        self.rows.sort(key=lambda r: (natural_chrom_key(r[0]), r[1], r[2], r[3]))
        with open(self.path, "w", encoding="utf-8", newline="\n") as out:
            if self.write_header:
                out.write(BED_HEADER_NOTE)
                out.write("# chrom\tstart\tend\tname\tscore\tstrand\t"
                          + "\t".join(self.extra_column_names) + "\n")
            for chrom, start, end, name, strand, extras in self.rows:
                # Score is fixed at 0. The BED spec restricts it to 0-1000 and
                # we have nothing meaningful to put there, so 0 is the honest
                # choice rather than abusing the field for an ID.
                out.write("{}\t{}\t{}\t{}\t0\t{}\t{}\n".format(
                    chrom, start, end, name, strand, "\t".join(extras)))
        count = len(self.rows)
        self.rows = []          # free the memory, these lists get large
        return count


# ---------------------------------------------------------------------------
# Stage 1: read the GTF into per-transcript records
# ---------------------------------------------------------------------------

def parse_gtf(gtf_path):
    """Single streaming pass over the GTF.

    Returns three things:
      genes        dict gene_id -> gene level record
      transcripts  dict transcript_id -> transcript level record, each of which
                   carries its own lists of exons, CDS blocks and stop codons
      gencode_utrs dict transcript_id -> list of UTR blocks straight from the
                   file, kept only so we can sanity check our own derivation
    """
    genes = {}
    transcripts = {}
    gencode_utrs = defaultdict(list)

    lines_seen = 0
    with open_maybe_gzip(gtf_path) as handle:
        for line in handle:
            # GTF comment and header lines start with '#'.
            if line[0] == "#":
                continue

            lines_seen += 1
            if lines_seen % 500000 == 0:
                log("  ...parsed {:,} GTF records".format(lines_seen))

            fields = line.rstrip("\n").split("\t")
            if len(fields) != 9:
                continue        # malformed line, skip it rather than crash

            chrom = fields[0]
            feature = fields[2]

            # Skip feature types we have no use for before doing the relatively
            # expensive attribute parsing. start_codon and Selenocysteine are
            # already implied by the CDS blocks.
            if feature not in ("gene", "transcript", "exon", "CDS",
                               "stop_codon", "UTR"):
                continue

            # The 1-based inclusive to 0-based half-open conversion, done once.
            start = int(fields[3]) - 1
            end = int(fields[4])
            strand = fields[6]
            attrs = parse_attributes(fields[8])

            if feature == "gene":
                gene_id = attrs.get("gene_id", "")
                genes[gene_id] = {
                    "chrom": chrom, "start": start, "end": end, "strand": strand,
                    "gene_id": gene_id,
                    # Some GTFs have no gene_name at all. Falling back to the ID
                    # keeps every row populated instead of leaving blanks that
                    # would shift columns in downstream text processing.
                    "gene_name": attrs.get("gene_name", gene_id),
                    "gene_type": attrs.get("gene_type", "NA"),
                }
                continue

            transcript_id = attrs.get("transcript_id", "")
            if not transcript_id:
                continue

            if feature == "transcript":
                transcripts[transcript_id] = {
                    "chrom": chrom, "start": start, "end": end, "strand": strand,
                    "transcript_id": transcript_id,
                    "transcript_name": attrs.get("transcript_name", transcript_id),
                    "transcript_type": attrs.get("transcript_type", "NA"),
                    "gene_id": attrs.get("gene_id", "NA"),
                    "gene_name": attrs.get("gene_name", attrs.get("gene_id", "NA")),
                    "exons": [],
                    "cds": [],
                    "stop_codons": [],
                }
            elif feature == "exon":
                # exon_number comes straight from the GTF and is already counted
                # in transcription order, so exon 1 is the 5'-most exon on a plus
                # strand transcript and the 3'-most coordinate on a minus strand
                # one. We keep it rather than recomputing it.
                exon_number = attrs.get("exon_number", "0")
                transcripts[transcript_id]["exons"].append((start, end, exon_number))
            elif feature == "CDS":
                exon_number = attrs.get("exon_number", "0")
                transcripts[transcript_id]["cds"].append((start, end, exon_number))
            elif feature == "stop_codon":
                transcripts[transcript_id]["stop_codons"].append((start, end))
            elif feature == "UTR":
                gencode_utrs[transcript_id].append((start, end))

    log("  finished reading, {:,} usable GTF records".format(lines_seen))
    return genes, transcripts, gencode_utrs


# ---------------------------------------------------------------------------
# Stage 2: derive the feature classes and write them out
# ---------------------------------------------------------------------------

def build_bed_files(genes, transcripts, gencode_utrs, outdir,
                    stop_codon_in_cds, write_header):
    """Derive every feature class and write one BED file per class."""

    writers = {
        "genes": BedWriter(
            os.path.join(outdir, "genes.bed"),
            ["gene_id", "gene_name", "gene_type"], write_header),
        "transcripts": BedWriter(
            os.path.join(outdir, "transcripts.bed"),
            ["transcript_id", "transcript_name", "gene_id", "gene_name",
             "transcript_type"], write_header),
        "exons": BedWriter(
            os.path.join(outdir, "exons.bed"),
            ["exon_number", "transcript_id", "transcript_name", "gene_id",
             "gene_name", "transcript_type"], write_header),
        "coding_exons": BedWriter(
            os.path.join(outdir, "coding_exons.bed"),
            ["exon_number", "transcript_id", "transcript_name", "gene_id",
             "gene_name", "transcript_type"], write_header),
        "five_utr": BedWriter(
            os.path.join(outdir, "five_prime_utrs.bed"),
            ["block_number", "transcript_id", "transcript_name", "gene_id",
             "gene_name", "transcript_type"], write_header),
        "three_utr": BedWriter(
            os.path.join(outdir, "three_prime_utrs.bed"),
            ["block_number", "transcript_id", "transcript_name", "gene_id",
             "gene_name", "transcript_type"], write_header),
        "introns": BedWriter(
            os.path.join(outdir, "introns.bed"),
            ["intron_number", "transcript_id", "transcript_name", "gene_id",
             "gene_name", "transcript_type"], write_header),
    }

    # ---- genes -------------------------------------------------------------
    log("Building genes.bed")
    for gene in genes.values():
        name = "{}|{}".format(gene["gene_id"], gene["gene_name"])
        writers["genes"].add(
            gene["chrom"], gene["start"], gene["end"], name, gene["strand"],
            (gene["gene_id"], gene["gene_name"], gene["gene_type"]))

    # ---- everything that is at the transcript level ----------------------
    log("Building transcript level features "
        "(transcripts, exons, coding exons, UTRs, introns)")

    stats = {
        "transcripts_total": 0,
        "transcripts_coding": 0,
        "transcripts_no_exons": 0,
        "single_exon_transcripts": 0,
        "utr_pieces_ambiguous": 0,
    }

    for tx in transcripts.values():
        stats["transcripts_total"] += 1
        chrom = tx["chrom"]
        strand = tx["strand"]
        gene_id = tx["gene_id"]
        gene_name = tx["gene_name"]
        tx_id = tx["transcript_id"]
        tx_name = tx["transcript_name"]
        tx_type = tx["transcript_type"]

        # This tuple of metadata is identical for every row belonging to this
        # transcript, so we build it once instead of inside each loop.
        meta_tail = (tx_id, tx_name, gene_id, gene_name, tx_type)

        # -- the transcript row itself --
        writers["transcripts"].add(
            chrom, tx["start"], tx["end"],
            "{}|{}|{}".format(tx_id, gene_id, gene_name), strand,
            (tx_id, tx_name, gene_id, gene_name, tx_type))

        # Sort exons by coordinate. GTF usually lists minus strand exons in
        # descending coordinate order, and every piece of interval arithmetic
        # below assumes ascending order, so we normalise here.
        exons = sorted(tx["exons"])
        if not exons:
            stats["transcripts_no_exons"] += 1
            continue
        if len(exons) == 1:
            stats["single_exon_transcripts"] += 1

        # -- exons (all of them, coding or not) --
        for exon_start, exon_end, exon_number in exons:
            writers["exons"].add(
                chrom, exon_start, exon_end,
                "{}|{}|exon{}".format(gene_name, tx_id, exon_number),
                strand, (exon_number,) + meta_tail)

        # -- introns: the gaps between consecutive exons --
        gaps = []
        for i in range(len(exons) - 1):
            gap_start = exons[i][1]        # BED end of this exon
            gap_end = exons[i + 1][0]      # BED start of the next exon
            if gap_end > gap_start:
                gaps.append((gap_start, gap_end))

        total_gaps = len(gaps)
        for index, (gap_start, gap_end) in enumerate(gaps):
            # Number introns in transcription order, matching how GTF numbers
            # exons. On the minus strand that means counting from the other end,
            # so that "intron1" is always the first intron the polymerase meets.
            intron_number = index + 1 if strand != "-" else total_gaps - index
            writers["introns"].add(
                chrom, gap_start, gap_end,
                "{}|{}|intron{}".format(gene_name, tx_id, intron_number),
                strand, (str(intron_number),) + meta_tail)

        # -- coding exons and UTRs --
        cds_blocks = sorted(tx["cds"])
        if not cds_blocks:
            # No CDS means a non-coding transcript (lncRNA, pseudogene, miRNA
            # and so on). It has exons and introns but no coding exons and, by
            # definition, no UTRs. Nothing further to do.
            continue

        stats["transcripts_coding"] += 1

        # Write the CDS blocks as the "coding exons". These are the translated
        # portions of exons, which is what people normally mean by a coding exon
        # when they contrast it with a UTR.
        for cds_start, cds_end, exon_number in cds_blocks:
            writers["coding_exons"].add(
                chrom, cds_start, cds_end,
                "{}|{}|CDS{}".format(gene_name, tx_id, exon_number),
                strand, (exon_number,) + meta_tail)

        # Decide what counts as "the coding region" for the purpose of carving
        # out UTRs. See the module docstring for why the default excludes the
        # stop codon.
        coding_blocks = [(s, e) for s, e, _ in cds_blocks]
        if stop_codon_in_cds and tx["stop_codons"]:
            coding_blocks = merge_intervals(coding_blocks + tx["stop_codons"])

        coding_min = min(s for s, e in coding_blocks)
        coding_max = max(e for s, e in coding_blocks)

        # UTR = exon minus coding. Whatever is left over from an exon after
        # removing the coding blocks is untranslated by construction.
        upstream_pieces = []     # left of the coding region in genome coordinates
        downstream_pieces = []   # right of the coding region
        for exon_start, exon_end, _ in exons:
            for piece_start, piece_end in subtract_intervals(
                    (exon_start, exon_end), coding_blocks):
                if piece_end <= coding_min:
                    upstream_pieces.append((piece_start, piece_end))
                elif piece_start >= coding_max:
                    downstream_pieces.append((piece_start, piece_end))
                else:
                    stats["utr_pieces_ambiguous"] += 1
                    if piece_start < coding_min:
                        upstream_pieces.append((piece_start, coding_min))
                    if piece_end > coding_max:
                        downstream_pieces.append((coding_max, piece_end))

        # Now translate "upstream / downstream in genome coordinates" into
        # "5' / 3' in transcript coordinates". 
      
        if strand == "-":
            five_prime_pieces = sorted(downstream_pieces, reverse=True)
            three_prime_pieces = sorted(upstream_pieces, reverse=True)
        else:
            five_prime_pieces = sorted(upstream_pieces)
            three_prime_pieces = sorted(downstream_pieces)

        for index, (piece_start, piece_end) in enumerate(five_prime_pieces, start=1):
            writers["five_utr"].add(
                chrom, piece_start, piece_end,
                "{}|{}|5UTR{}".format(gene_name, tx_id, index),
                strand, (str(index),) + meta_tail)

        for index, (piece_start, piece_end) in enumerate(three_prime_pieces, start=1):
            writers["three_utr"].add(
                chrom, piece_start, piece_end,
                "{}|{}|3UTR{}".format(gene_name, tx_id, index),
                strand, (str(index),) + meta_tail)

    # ---- write everything to disk -----------------------------------------
    counts = {}
    for key in ["genes", "transcripts", "exons", "coding_exons",
                "five_utr", "three_utr", "introns"]:
        counts[key] = writers[key].flush()
        log("  wrote {:>9,} rows to {}".format(
            counts[key], os.path.basename(writers[key].path)))

    return counts, stats


# ---------------------------------------------------------------------------
# Stage 3: sanity check our derived UTRs against the ones GENCODE ships
# ---------------------------------------------------------------------------

def validate_against_gencode_utrs(transcripts, gencode_utrs, stop_codon_in_cds):
    """Compare our derived UTR blocks with the GTF's own UTR lines.
    """
    if not gencode_utrs:
        return None

    matched = 0
    ours_only = 0
    theirs_only = 0
    transcripts_checked = 0

    for tx_id, their_blocks in gencode_utrs.items():
        tx = transcripts.get(tx_id)
        if tx is None or not tx["cds"]:
            continue
        transcripts_checked += 1

        exons = sorted(tx["exons"])
        cds_blocks = sorted((s, e) for s, e, _ in tx["cds"])
        if stop_codon_in_cds and tx["stop_codons"]:
            cds_blocks = merge_intervals(cds_blocks + tx["stop_codons"])

        ours = set()
        for exon_start, exon_end, _ in exons:
            for piece in subtract_intervals((exon_start, exon_end), cds_blocks):
                ours.add(piece)

        theirs = set(their_blocks)
        matched += len(ours & theirs)
        ours_only += len(ours - theirs)
        theirs_only += len(theirs - ours)

    return {
        "transcripts_checked": transcripts_checked,
        "blocks_matching": matched,
        "blocks_only_in_ours": ours_only,
        "blocks_only_in_gencode": theirs_only,
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Extract transcriptome features from a GTF into BED files.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--gtf", required=True,
                        help="Input GTF file, plain or gzipped.")
    parser.add_argument("--outdir", required=True,
                        help="Directory to write the BED files into.")
    parser.add_argument("--stop-codon-in-cds", action="store_true",
                        help="Count the stop codon as coding sequence instead "
                             "of as part of the 3'UTR. GENCODE's own UTR lines "
                             "put it in the 3'UTR, which is the default here.")
    parser.add_argument("--header", action="store_true",
                        help="Write '#' comment header lines into each BED "
                             "file.")
    parser.add_argument("--skip-validation", action="store_true",
                        help="Skip the UTR self check against the GTF's own "
                             "UTR lines.")
    args = parser.parse_args()

    if not os.path.isdir(args.outdir):
        os.makedirs(args.outdir)

    started = time.time()

    log("Reading GTF: {}".format(args.gtf))
    genes, transcripts, gencode_utrs = parse_gtf(args.gtf)
    log("Found {:,} genes and {:,} transcripts".format(
        len(genes), len(transcripts)))

    counts, stats = build_bed_files(
        genes, transcripts, gencode_utrs, args.outdir,
        args.stop_codon_in_cds, args.header)

    # ---- report -----------------------------------------------------------
    report_lines = []
    report_lines.append("GTF to BED extraction report")
    report_lines.append("=" * 60)
    report_lines.append("Input GTF          : {}".format(os.path.abspath(args.gtf)))
    report_lines.append("Output directory   : {}".format(os.path.abspath(args.outdir)))
    report_lines.append("Stop codon treated as: {}".format(
        "CDS" if args.stop_codon_in_cds else "3'UTR (GENCODE convention)"))
    report_lines.append("")
    report_lines.append("Feature counts (rows per BED file)")
    report_lines.append("-" * 60)
    label_for = {
        "genes": "genes.bed",
        "transcripts": "transcripts.bed",
        "exons": "exons.bed",
        "coding_exons": "coding_exons.bed",
        "five_utr": "five_prime_utrs.bed",
        "three_utr": "three_prime_utrs.bed",
        "introns": "introns.bed",
    }
    for key in ["genes", "transcripts", "exons", "coding_exons",
                "five_utr", "three_utr", "introns"]:
        report_lines.append("  {:<24} {:>12,}".format(label_for[key], counts[key]))

    report_lines.append("")
    report_lines.append("Transcript level statistics")
    report_lines.append("-" * 60)
    report_lines.append("  transcripts total       {:>12,}".format(stats["transcripts_total"]))
    report_lines.append("  with a CDS (coding)     {:>12,}".format(stats["transcripts_coding"]))
    report_lines.append("  non-coding              {:>12,}".format(
        stats["transcripts_total"] - stats["transcripts_coding"]))
    report_lines.append("  single exon (no intron) {:>12,}".format(stats["single_exon_transcripts"]))
    report_lines.append("  with no exon lines      {:>12,}".format(stats["transcripts_no_exons"]))
    report_lines.append("  ambiguous UTR pieces    {:>12,}".format(stats["utr_pieces_ambiguous"]))

    if not args.skip_validation:
        log("Validating derived UTRs against the GTF's own UTR lines")
        validation = validate_against_gencode_utrs(
            transcripts, gencode_utrs, args.stop_codon_in_cds)
        if validation:
            total = validation["blocks_matching"] + validation["blocks_only_in_ours"]
            percent = 100.0 * validation["blocks_matching"] / total if total else 0.0
            report_lines.append("")
            report_lines.append("UTR self check against the GTF's own UTR lines")
            report_lines.append("-" * 60)
            report_lines.append("  coding transcripts checked   {:>12,}".format(
                validation["transcripts_checked"]))
            report_lines.append("  identical UTR blocks         {:>12,}".format(
                validation["blocks_matching"]))
            report_lines.append("  only in our derivation       {:>12,}".format(
                validation["blocks_only_in_ours"]))
            report_lines.append("  only in the GTF              {:>12,}".format(
                validation["blocks_only_in_gencode"]))
            report_lines.append("  agreement                    {:>11.4f}%".format(percent))

    report_lines.append("")
    report_lines.append("Elapsed: {:.1f} s".format(time.time() - started))

    report = "\n".join(report_lines)
    print(report)

    report_path = os.path.join(args.outdir, "extraction_report.txt")
    with open(report_path, "w", encoding="utf-8", newline="\n") as out:
        out.write(report + "\n")
    log("Report written to {}".format(report_path))


if __name__ == "__main__":
    main()
